// <auto-generated />
namespace BucketList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletedatabasetofixloginprobs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedatabasetofixloginprobs));
        
        string IMigrationMetadata.Id
        {
            get { return "201611111906564_delete data base to fix login probs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
